### ISSUE TITLE
RuntimeError: application not registered on db instance

### ISSUE THREAD

**Issue by pramttl** [pramttl/mirror-sync-api#29]
#### `reorganize` branch :cactus:  only

Just to put things into perspective as to when the error occurs:
This error occurs after the master node has synced up from the upstream source and the `sync_project_from_upstream` function is being called.

It is unable to fetch a queryset of all the slave nodes in the function `sync_project_from_upstream`. Queries before this had ran successfully. But only in this function it happens that flask_sqlalchemy starts complaining about the application context. Maybe because this function is not a view function directly but a utility function called from a view function. I am not sure why, but this is the line at which the error occurs:
##### Line:

```
ftp_hosts = SlaveNode.query.all()
```
##### Traceback

```
INFO:werkzeug:127.0.0.1 - - [30/Jun/2014 03:44:14] "POST /add_project/ HTTP/1.1" 200 -
Syncing up ubuntu
Rsync complete
ERROR:apscheduler.scheduler:Job "sync_project_from_upstream (trigger: cron[minute='*'], next run at: 2014-06-30 03:46:00)" raised an exception
Traceback (most recent call last):
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "master/master.py", line 55, in sync_project_from_upstream
    ftp_hosts = SlaveNode.query.all()
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 428, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 70, in __call__
    return self.registry()
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 903, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 136, in __init__
    self.app = db.get_app()
  File "/home/pranjal/projects/osl/mirror-sync-api/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 809, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

**Comment by pramttl** [comment]
Might be helpful to understand:
http://flask.pocoo.org/docs/appcontext/
